name: elektrophon
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.2.*
  - python=3.9.*
  - numpy=1.21.1
  - ipykernel
  - jupyter=*
  - jupyterlab=*
  - notebook=6.4.0
  - nbconvert=6.*
  - scipy=1.7.*
  - sympy=1.8.*
  - ngspice-lib=32
  - pyspice=1.4.*
  - pandas=1.3.1
  - nodejs=*
  - pytest=6.*.*
  - pytest-json=0.4.*
  - scons=4.2.*
  - pylint=2.9.*
  - junit-xml=1.9
  - pip:
    - schemdraw
    - itikz
    - ipytest
    - nbflow
