name: elektrophon
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=21.0.*
  - python=3.9.*
  - numpy=1.19.*
  - ipykernel
  - jupyter=*
  - notebook=6.2.*
  - nbconvert=6.*
  - scipy=1.6.*
  - sympy=1.7.*
  - ngspice-lib=32
  - pyspice=1.4.
  - pandas=1.2.*
  - nodejs=*
  - pip:
    - schemdraw
    - itikz
